name: "test"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9, 3.1, 3.11, 3.12]
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - uses: gerbal/always-cache@v1.0.3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-24.2-1.8.3-1.0.6
          restore-keys: pip-cache-
      - run: pip install pip==24.2
      - run: pip install poetry==1.8.3
      - run: pip install envo==1.0.6
      - uses: actions/cache@v2
        id: root-venv-cache
        with:
          path: |
            .venv
            tests/test_srvs/app_srv/.venv
            tests/test_srvs/django_srv/.venv
            tests/test_srvs/flask_srv/.venv
          key: root-venv-v3-${{ hashFiles('poetry.lock') }}
          restore-keys: root-venv-v3-
      - name: Bootstrap repo
        run: envo ci run p.bootstrap
      - name: test
        run: envo ci run p.test

  publish:
    env:
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - uses: gerbal/always-cache@v1.0.3
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-cache-24.2-1.8.3-1.0.6
          restore-keys: pip-cache-
      - run: pip install pip==24.2
      - run: pip install poetry==1.8.3
      - run: pip install envo==1.0.6
      - uses: actions/cache@v2
        id: root-venv-cache
        with:
          path: |
            .venv
            tests/test_srvs/app_srv/.venv
            tests/test_srvs/django_srv/.venv
            tests/test_srvs/flask_srv/.venv
          key: root-venv-v3-${{ hashFiles('poetry.lock') }}
          restore-keys: root-venv-v3-
      - name: Bootstrap repo
        run: envo ci run "p.bootstrap(test_apps=False)"
      - name: Generate version
        run: envo ci run p.generate_version
      - name: Build
        run: envo ci run p.build
      - name: Publish
        run: envo ci run p.publish